add configmaps to watched nic resources
Azure/aks-app-routing-operator pull request #139
Opened 2023-11-21 21:24 UTC by OliverMKing

# Description

Triggers a reconcile on nic resources when a managed configmap is updated.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

E2e and unit tested. This is a core feature of how controller runtime works. It doesn't make sense to try to write a unit test for something already tested in the controller runtime package.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-11-21 21:34 UTC, OliverMKing commented
/ok-to-test sha=1799336

2023-11-28 19:15 UTC, jaiveerk requested changes

2023-11-28 19:15 UTC, jaiveerk commented on pkg/controller/nginxingress/nginx_ingress_controller.go
> +			Owns(&corev1.ConfigMap{}),  // we don't use this to update any statuses but we do want to immediatley overwrite any user changes. it's not supported for users to edit the configmap
nit: typo

2024-03-18 14:13 UTC, tuananhnguyen-ct commented
Is there anyway to defer this until https://github.com/Azure/aks-app-routing-operator/issues/168 is addressed?

2024-05-28 15:16 UTC, OliverMKing commented
/ok-to-test sha=46937e0

2024-05-28 15:23 UTC, OliverMKing commented
/ok-to-test sha=e045c7a

2024-06-13 13:46 UTC, OliverMKing commented
/ok-to-test sha=c345e00

2024-06-13 15:06 UTC, OliverMKing commented
/ok-to-test sha=16540c1

2024-06-19 13:41 UTC, OliverMKing commented
/ok-to-test sha=07cd5d8

2024-06-19 14:05 UTC, OliverMKing commented
/ok-to-test sha=07cd5d8

2024-06-19 14:06 UTC, OliverMKing commented
/ok-to-test sha=7d31cb3

2024-08-30 18:14 UTC, closed without merging