Adding Ingress Controller Labels for Metrics to Ingress Controller Pods
Azure/aks-app-routing-operator pull request #49
Opened 2023-04-25 20:56 UTC by jaiveerk

# Description

Adding the following labels to pods deployed as part of WAR's ingress controller deployments to be able to query metrics from them without scraping the pods directly. 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration. Is it a breaking change which will impact consuming tool(s)?

Unit tests have been added to ensure that changes to fixtures are limited to what they're intended to be.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-04-25 22:40 UTC, bfoley13 approved these changes
Looks clean

2023-04-26 15:00 UTC, OliverMKing requested changes

2023-04-26 15:08 UTC, jaiveerk commented on pkg/manifests/nginx.go
> +	tr["app.kubernetes.io/managed-by"] = "aks-app-routing-operator"
fair point, but check out line 295 - this method also needs to work for pod labels. 

I can just duplicate this code in the newNginxIngressControllerDeployment method to add the component label to the top level labels, or, I suppose if we want to propagate the component label to other metrics, I can make a separate method for that and just call that, I'm just not sure about introducing the component label right now - it's out of scope for this PR and makes its purpose unclear (adding necessary labels for metrics in AKS-operator vs introducing a new labeling scheme that unnecessarily adds complexity).

If you feel strongly about using the component label everywhere I can do that, just given my history of PRs in this repo I'm weary of adding complexity where it isn't immediately necessary.

2023-04-26 15:36 UTC, jaiveerk commented on pkg/manifests/nginx.go
> +	tr["app.kubernetes.io/managed-by"] = "aks-app-routing-operator"
After offline discussion I'll just add in the component label

2023-04-26 16:58 UTC, OliverMKing submitted a review, later dismissed

2023-04-26 19:02 UTC, OliverMKing commented on pkg/manifests/nginx.go
> +func addComponentLabel(originalLabels map[string]string, componentName string) map[string]string {
Since this was generalized it probably makes more sense in `common.go`

2023-04-26 19:59 UTC, OliverMKing approved these changes

2023-04-26 21:52 UTC, davidgamero approved these changes

2023-04-26 21:53 UTC, bfoley13 approved these changes

2023-04-26 21:54 UTC, jaiveerk commented on pkg/manifests/nginx_test.go
> +	if withAdditions["app.kubernetes.io/component"] != "ingress-controller" {
good call!

2023-04-26 21:55 UTC, davidgamero submitted a review, later dismissed

2023-04-26 21:57 UTC, bfoley13 approved these changes

2023-04-27 14:43 UTC, jaiveerk commented on pkg/manifests/fixtures/nginx/full.json
> +          "app.kubernetes.io/component": "ingress-controller-cluster-role-binding"
done, generalized component to ingress-controller

2023-04-27 14:58 UTC, OliverMKing approved these changes

2023-04-27 15:35 UTC, davidgamero approved these changes

2023-04-27 15:46 UTC, merged